[package]
name = "hermit"
version = "0.10.0"
authors = [
    "Stefan Lankes <slankes@eonerc.rwth-aachen.de>",
    "Martin Kröning <mkroening@posteo.net>",
]
edition = "2021"
description = "The Hermit unikernel for Rust."
repository = "https://github.com/hermit-os/hermit-rs"
license = "MIT OR Apache-2.0"
keywords = ["unikernel", "libos"]
categories = ["os"]
links = "hermit"

[features]
default = [
    "acpi",
    "dhcpv4",
    "fs",
    "fsgsbase",
    "pci",
    "pci-ids",
    "smp",
    "tcp",
    "udp",
    "dns",
]

acpi = []
dhcpv4 = []
dns = []
fs = []
fsgsbase = []
idle-poll = []

# Build the kernel with function instrument code for mcount-based tracing
instrument = []

libc = []
mmap = []
pci = []
pci-ids = ["pci"]

# Enables -Z randomize-layout in the kernel
randomize-layout = []

# if this feature isn't set, the Virtio interface will be used
rtl8139 = ["pci"]

shell = []
smp = []
strace = []
tcp = []
trace = []
udp = []
vga = []
vsock = []

[build-dependencies]
cc = "1"
flate2 = "1"
ureq = "3"
tar = "0.4"
